### ISSUE TITLE
AM232X lib dependency missing

### ISSUE THREAD

**Issue by vortigont** [vladkorotnev/plasma-clock#24]
Project does not builds without `AM232X` lib
adding
```
lib_deps =
    robtillaart/AM232X
```

fixes it, though I'm not sure why it is missing there

**Comment by vladkorotnev** [comment]
That is added via submodules, I didn't know it's available on PIO. You can solve it by cloning the repo with the recurse-submodules option to Git. But I will fix this to PIO later, or if you could do a PR I'll merge it! (Away from PC for the rest of the week)
